language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
install:
  - "pip install -e ."
  - "pip install -r requirements.txt"
script: nosetests --with-coverage --cover-erase --cover-package=pyserializer
after_success: coveralls
